<?php

use Illuminate\Database\Seeder;

class DashboardNotificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lists = collect([
            [ //Account Approved - Vendor
                'notification_event_id' => 9,
                'frequency' => 'realtime,summary',
                'subject' => 'Congratulations, your account has been approved!',
                'body' => 'Congratulations, your account has been approved and is now live! You\'re ready to start winning work!',
                'button' => 'FIND WORK',
                'button_link' => '/dashboard/job-posts',
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Account Approved - Vendor
                'notification_event_id' => 9,
                'frequency' => 'realtime,summary',
                'subject' => 'Update your business settings!',
                'body' => 'So that you are ready to start earning revenue, update your business & notification settings.',
                'button' => 'UPDATE SETTINGS',
                'button_link' => '/user-settings',
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Account Pending - Vendor
                'notification_event_id' => 47,
                'frequency' => 'realtime,summary',
                'subject' => 'Your account is being reviewed',
                'body' => 'We are reviewing your account & will contact you about your application soon. In the meantime, finish setting up your profile!',
                'button' => 'Set Up My Profile',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Invoice Received - Couple
                'notification_event_id' => 34,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Invoice received from [business_name]',
                'body' => 'You\'ve accepted the quote from [business_name]. Pay the deposit to confirm the booking!',
                'button' => 'View',
                'button_link' => '/dashboard',
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Invoice Sent - Vendor
                'notification_event_id' => 35,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Invoice sent',
                'body' => 'Auto generated invoice was sent to [profile_title]',
                'button' => 'View',
                'button_link' => '/dashboard',
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => '[profile_title]',
                'type' => 'dashboard'
            ],
            [ //New Job Request - Single - Vendor
                'notification_event_id' => 5,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[couple_title] have requested a quote from you',
                'body' => 'View their job details and send them a quote if you\'re available.',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //New Job Quote - Couple
                'notification_event_id' => 8,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Quote from [business_name]',
                'body' => 'You have received a quote for your "[category_name]" job for your "[event_name]"',
                'button' => 'View',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[category_name],[event_name]',
                'type' => 'dashboard'
            ],
            [ //Job Quote Extended
                'notification_event_id' => 37,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your quote from [business_name] has been extended',
                'body' => 'You have more time to consider this quote, review it now.',
                'button' => 'Login To My wedBooker Account',
                'button_link' => '/dashboard',
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Response - accepted
                'notification_event_id' => 38,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[couple_title] have accepted your quote',
                'body' => 'The invoice has been sent. Once they pay the deposit, the booking will be confirmed.',
                'button' => 'Login To My wedBooker Account',
                'button_link' => '/dashboard',
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Response - request changes
                'notification_event_id' => 39,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[couple_title] has requested to change your quote',
                'body' => 'Review their change requests',
                'button' => 'Login To My wedBooker Account',
                'button_link' => '/dashboard',
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Response - declined
                'notification_event_id' => 40,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[couple_title] has declined your quote',
                'body' => 'Your quote for "[couple_title] looking for [category_name]" was declined',
                'button' => 'Login To My wedBooker Account',
                'button_link' => '/dashboard',
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title],[category_name]',
                'type' => 'dashboard'
            ],
            [ //New Job Post - Favourite - Vendor
                'notification_event_id' => 41,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'High job match! You are one of the favourite businesses for [couple_title]\'s new job!',
                'body' => '[couple_title] love your work. Quote on their job today!',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //New Job Approved - Vendor
                'notification_event_id' => 42,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Job match for your business!',
                'body' => '[couple_title] are looking for [category] for their event. View their job and submit a quote!',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => '[couple_title],[category]',
                'type' => 'dashboard'
            ],
            [ //New Job Request - Multiple - Vendor
                'notification_event_id' => 6,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'A new job from [couple_title] is well suited to your business!',
                'body' => 'View this job and quote on it today!',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title],[category]',
                'type' => 'dashboard'
            ],
            [ //New Favourite - Vendor
                'notification_event_id' => 46,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'JOB ALERT: HIGH MATCH FOR YOUR BUSINESS',
                'body' => '[couple_title] are looking for a [category]. Plus they have listed you as one of their favourite businesses. Be sure to submit your quote today!',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title],[category]',
                'type' => 'dashboard'
            ],
            [ //Email Verified - Couple
                'notification_event_id' => 3,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Save your favourite Suppliers & Venues',
                'body' => 'Quick tip! When browsing our Suppliers & Venues, you can click the heart button on your favourite businesses. We\'ll then invite them to quote on your jobs!',
                'button' => 'Browse Suppliers & Venues',
                'button_link' => '/suppliers-and-venues',
                'recipient' => 'couple',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Email Verified - Couple
                'notification_event_id' => 3,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Welcome to wedBooker!',
                'body' => 'Let\'s help you start planning your wedding! You can browse our Suppliers & Venues and request quotes from the ones you fancy, or you can post a job and we will match you with the Suppliers & Venues best suited to your needs!',
                'button' => 'Post a Job',
                'button_link' => '/dashboard/job-posts/create',
                'button2' => 'Browse Suppliers & Venues',
                'button_link2' => '/suppliers-and-venues',
                'recipient' => 'couple',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Email Verified - Profile Picture - Couple
                'notification_event_id' => 43,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Say cheese!',
                'body' => 'Let\'s get your profile looking fancy. Upload a pretty pic of you and your partner to personalise your account!',
                'button' => 'Upload Profile Picture',
                'button_link' => '',
                'recipient' => 'couple',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //New Job Post - Couple
                'notification_event_id' => 7,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Thanks For Posting Your [category_name] Job',
                'body' => 'Thanks For Posting Your [category_name] Job',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[category_name]',
                'tokens_body' => '[category_name]',
                'type' => 'dashboard'
            ],
            [ //Job Post Expiration Reminder - Couple
                'notification_event_id' => 26,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your job is about to expire',
                'body' => 'There has been no recent activity on your [category_name] job. If you would still like to book this, you can always extend your job.',
                'button' => 'Extend Job',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => null,
                'tokens_body' => '[category_name]',
                'type' => 'dashboard'
            ],
            [ //Job Expired - Couple
                'notification_event_id' => 19,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your job has expired',
                'body' => 'There was no activity on your [category_name] job. If you’d still like to make this booking, you can set your job live again.',
                'button' => 'Set Job Live',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => null,
                'tokens_body' => '[category_name]',
                'type' => 'dashboard'
            ],
            [ //Email Verified - Vendor
                'notification_event_id' => 3,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Thanks for signing up with wedBooker!',
                'body' => 'We are reviewing your account & will contact you about your application soon. In the meantime, finish setting up your profile!',
                'button' => 'Setup My Profile',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Email Verified - Review - Vendor
                'notification_event_id' => 45,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Build your star rating to win more work!',
                'body' => 'Provide the email address of two past couples who have booked your services, so they can review your business. It only takes 2 minutes. These reviews will then show on your profile to help you win more work.',
                'button' => 'Build My Reviews',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Offer Expired - Vendor
                'notification_event_id' => 17,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your wedBooker Exclusive Offer requires your attention',
                'body' => 'The offer on your wedBooker profile has now expired. Make sure you remove your offer from your profile page or extend the expiry date.',
                'button' => 'Update Offer',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Payment Reminder - Couple
                'notification_event_id' => 11,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Payment reminder from [business_name]',
                'body' => 'Hi [couple_title], hope the wedding planning is going well. A friendly reminder to pay the amount owing on your invoice as soon as possible. You can click here to view and pay the invoice. Thanks, [business_name]',
                'button' => 'View Invoice & Pay Now',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[couple_title],[business_name]',
                'type' => 'dashboard'
            ],
            [ //Balance Due Reminder - Couple
                'notification_event_id' => 33,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[business_name] has sent you a payment reminder',
                'body' => 'You have a payment owing to [business_name] for your [category_name] booking.',
                'button' => 'View Invoice & Pay',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name],[category_name]',
                'type' => 'dashboard'
            ],
            [ //Send Vendor Review To Couples - Couple
                'notification_event_id' => 32,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'How do you rate [vendor_title]?',
                'body' => 'Please review this business to help other couples choose the best businesses for their big day.',
                'button' => 'Review now',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[vendor_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Expired - Vendor
                'notification_event_id' => 18,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your quote for [couple_title] has expired',
                'body' => 'Your quote for [couple_title] has expired. You can extend the quote to give them more time to respond by editing the expiry date in your quote.',
                'button' => 'Extend Quote',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Job Quote Expired - Couple
                'notification_event_id' => 18,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your quote from [business_name] has expired',
                'body' => 'Your quote from [business_name] has expired. You can request for them to extend the quote to by logging in and sending them a message.',
                'button' => 'Message Business',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Booking Confirmed - Vendor
                'notification_event_id' => 10,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking is confirmed',
                'body' => '[couple_title] made payment and this booking is now confirmed',
                'button' => 'View Booking',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Booking Confirmed - Couple
                'notification_event_id' => 10,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking with [business_name] is confirmed',
                'body' => 'Your payment has been received and your booking is confirmed.',
                'button' => 'View Booking',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Balance Paid - Vendor
                'notification_event_id' => 23,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => '[couple_title] has paid the final balance',
                'body' => 'Make sure you are ready for their booking.',
                'button' => 'View Booking',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Balance Paid - Couple
                'notification_event_id' => 23,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'You have paid [business_name] in full',
                'body' => 'Make sure you keep in touch with them about any booking details.',
                'button' => 'View Booking',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Booking Cancelled - Vendor
                'notification_event_id' => 24,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking with [couple_title] has been cancelled',
                'body' => 'Your booking with [couple_title] has been cancelled. Please contact us at hello@wedbooker.com if you need any further information.',
                'button' => 'Message Them',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Booking Cancelled - Couple
                'notification_event_id' => 24,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking with [business_name] has been cancelled',
                'body' => 'Your booking with [business_name] has been cancelled. For more information, contact us at hello@wedbooker.com',
                'button' => 'Message Them',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Booking Refunded - Vendor
                'notification_event_id' => 13,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'We have refunded [couple_title] for their cancelled booking',
                'body' => 'We have refunded [couple_title] for their cancelled booking. Please contact us at hello@wedbooker.com if you need any further information.',
                'button' => 'Contact Us',
                'button_link' => 'mailto:hello@wedbooker.com',
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Booking Refunded - Couple
                'notification_event_id' => 13,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'We have refunded you for your cancelled booking with [business_name]',
                'body' => 'We have refunded you for your cancelled booking with [business_name]. Please contact us at hello@wedbooker.com if you need any further information.',
                'button' => 'Contact Us',
                'button_link' => 'mailto:hello@wedbooker.com',
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Job Quote Expiration Reminder - Vendor
                'notification_event_id' => 27,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your quote for [couple_title] expires in 3 days',
                'body' => 'Would you like to give them more time? Extend the expiry date in your quote.',
                'button' => 'Extend Expiry Date',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Expiration Reminder - Couple
                'notification_event_id' => 27,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your quote from [business_name] expires in 3 days',
                'body' => 'Still thinking about this quote? Send them a message to request an extension.',
                'button' => 'Message Business',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Quote Updated - Couple
                'notification_event_id' => 44,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Updated Quote From [business_name]',
                'body' => 'You have received an updated quote for [couple_title] looking for [category_name]',
                'button' => 'View Quote',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[couple_title],[category_name]',
                'type' => 'dashboard'
            ],
            [ //Job Quote Updated - Vendor
                'notification_event_id' => 44,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your updated quote has been sent to [couple_title]',
                'body' => 'We\'ll let you know when they respond',
                'button' => 'View My Quote',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
            [ //Job Match Reminder - Vendor
                'notification_event_id' => 48,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Reminder: Job From [couple_title]',
                'body' => '[couple_title] is waiting for you to send them a quote.',
                'button' => 'View Job',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Job Quote Reminder - Couple
                'notification_event_id' => 49,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Reminder: Job Quote From [business_name]',
                'body' => '[business_name] is waiting for your response to their quote.',
                'button' => 'View Quote',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Review Received - Vendor
                'notification_event_id' => 20,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'New Review Received From [couple_title]',
                'body' => '[couple_title] has sent your business a review from your past event.',
                'button' => 'View Review',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Booking Date Reminder - Vendor
                'notification_event_id' => 25,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking for [couple_title] is coming up',
                'body' => 'Your booking for [couple_title] is coming up. Make sure you are ready for their event. We recommend reaching out to the couple to touch base.',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Booking Date Reminder - Couple
                'notification_event_id' => 25,
                'email_template_id' => 2,
                'frequency' => 'realtime',
                'subject' => 'Your booking with [business_name] is coming up',
                'body' => 'Your booking with [business_name] is coming up. If you haven\'t yet, we recommend touching base with them to confirm your booking details..',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Refund Requested by Couple - Vendor
                'notification_event_id' => 36,
                'frequency' => 'realtime',
                'subject' => '[couple_title] has requested for refund.',
                'body' => '[couple_title] has request a refund in your event. wedBooker will review this before confirming.',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Refund Requested by Couple - Couple
                'notification_event_id' => 36,
                'frequency' => 'realtime',
                'subject' => 'You have requested a refund from [business_name].',
                'body' => 'You have requested a refund for your event from [business_name]. wedBooker will review this before confirming.',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Refund Requested by Business - Vendor
                'notification_event_id' => 52,
                'frequency' => 'realtime',
                'subject' => 'You have issued a refund to [couple_title].',
                'body' => 'You have issued a refund for your event to [couple_title].',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'vendor',
                'tokens_subject' => '[couple_title]',
                'tokens_body' => '[couple_title]',
                'type' => 'dashboard'
            ],
            [ //Refund Requested by Business - Couple
                'notification_event_id' => 52,
                'frequency' => 'realtime',
                'subject' => '[business_name] has issued your refund.',
                'body' => '[business_name] has issued a refund in your event.',
                'button' => 'Message Now',
                'button_link' => null,
                'recipient' => 'couple',
                'tokens_subject' => '[business_name]',
                'tokens_body' => '[business_name]',
                'type' => 'dashboard'
            ],
            [ //Business First Qoute - Vendor
                'notification_event_id' => 53,
                'frequency' => 'realtime',
                'subject' => 'Add your bank details to get paid promptly',
                'body' => 'Thanks for quoting on your first job! When you have a minute to spare, add your bank details to your account settings to make sure you get paid promptly into your account for any work you win on wedBooker!',
                'button' => 'Add bank details',
                'button_link' => '/user-settings/payment',
                'recipient' => 'vendor',
                'tokens_subject' => null,
                'tokens_body' => null,
                'type' => 'dashboard'
            ],
        ])->reduce(function ($lists, $list) {
            $lists[] = [
                'notification_event_id' => $list['notification_event_id'],
                'frequency' => $list['frequency'],
                'subject' => $list['subject'],
                'body' => $list['body'],
                'button' => $list['button'],
                'button_link' => $list['button_link'],
                'button2' => isset($list['button2']) ? $list['button2'] : null,
                'button_link2' => isset($list['button_link2']) ? $list['button_link2'] : null, 
                'recipient' => $list['recipient'],
                'tokens_subject' => $list['tokens_subject'],
                'tokens_body' => $list['tokens_body'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'type' => $list['type'],
            ];

            return $lists;
        });

        DB::table('dashboard_notifications')->insert($lists);
    }
}
